### ISSUE TITLE
Odroid N2(+) not in supported downloads

### ISSUE THREAD

**Issue by NicoD-SBC** [armbian/mirror#11]
The Odroid N2(+) isn't in supported downloads. https://www.armbian.com/download/?device_support=Supported
Seems it's set to csc. Seems weird to me since it's one of the more popular boards. Ricardo is mentioned as maintainer.

**Comment by EvilOlaf** [comment]
Was wondering how you managed to open an issue on mirror repo while my link was pointing to build but then I realized that it is linked via "Issue with infrastructure" :smile: 

Anyway config was renamed to csc here: https://github.com/armbian/build/commit/8dee103d8f36f82522e796d599d22d9ef44b2e3c
I guess all boards were put to csc that had no maintainer attached in the config file. Don't know if Ricardo still does maintainership for it.

**Comment by igorpecovnik** [comment]
this was also resolved, at least download is not missing.Otherwise this mirror repo tracker should be more related to mirrors, not to providing particular images. This is defined here https://github.com/armbian/os/tree/main/userpatches
