### ISSUE TITLE
rsync error when syncing apt from rsync.armbian.com

### ISSUE THREAD

**Issue by Nardol** [armbian/mirror#12]
When running `rsync -avhr rsync://rsync.armbian.com/apt apt` to sync my mirror I get the following error:

```
@ERROR: chroot failed
rsync error: error starting client-server protocol (code 5) at main.c(1817) [Receiver=3.2.3]
```

Even if I can successfully sync beta and dl from rsync.armbian.com

I sent some message on Discord but without answer I create an issue here hoping it is a better place.

**Comment by igorpecovnik** [comment]
Fixed. 

We are moving services and apt was not tested ... It was a typo in config file ... sync will be very slow for at least a week due to high volume sparked by new release.
