### ISSUE TITLE
packages.ubuntu.com  Internal Server Error

### ISSUE THREAD

**Issue by cnwyx** [armbian/mirror#18]
https://packages.ubuntu.com/jammy-updates/amd64/base-files/download

![image](https://github.com/armbian/mirror/assets/18470410/d624d633-24de-495f-9151-d60eabceee5d)

😞 Are there any known alternatives or mirrors?

**Comment by igorpecovnik** [comment]
Unrelated to Armbian, Ubuntu bug.
