### ISSUE TITLE
Missing current linux-headers for sunxi64 

### ISSUE THREAD

**Issue by pavels** [armbian/mirror#24]
This may be problem with other sunxi64 images but i encountered it with BIGTREETECH CB1 image.

Latest available image to download is Armbian 24.8.1 with kernel 6.6.44 but latest linux-headers-current-sunxi64 package in the repository is linux-headers-current-sunxi64_24.5.4_arm64__6.6.36 - therefore if you need kernel headers on the CB1 with latest available image, you can't install them using apt as the package is missing from the repository.

As a side note - so does linux-image-current-sunxi64 and linux-dtb-current-sunxi64 - the packages in the image is newer than latest packages in the repository, so if you need to reinstall them for some reason, the only way to do it is either take them from the image or reflash image, they are not present in the apt repo.

**Comment by igorpecovnik** [comment]
Should be fixed now. Please update packages and install it once again, close the ticket if things are alright.
