### ISSUE TITLE
Failed to fetch http://armbian.lv.auroradev.org

### ISSUE THREAD

**Issue by sunjam** [armbian/mirror#4]
Having the issue while attempting to install Diet Pi on and Odroid C2.  See https://github.com/MichaIng/DietPi/issues/5190

**Comment by MichaIng** [comment]
I can confirm the `armbian.lv.auroradev.org` mirror is down.

**Comment by igorpecovnik** [comment]
I have removed it from APT but forgot about DL. We need to automate this ...
