### ISSUE TITLE
Mirror stpete-mirror.armbian.com slow/not available

### ISSUE THREAD

**Issue by mrtwiste** [armbian/mirror#8]
Hi, it seems that the mirror stpete-mirror.armbian.com is not more available.
Verbindung mit stpete-mirror.armbian.com:80 konnte nicht aufgebaut werden (188.227.12.37), Zeitüberschreitung aufgetreten

**Comment by igorpecovnik** [comment]
Looks fine:

https://check-host.net/check-http?host=https://stpete-mirror.armbian.com/

**Comment by igorpecovnik** [comment]
Closing since it was probably some temporally network issue.
