### ISSUE TITLE
Query regarding mirror 

### ISSUE THREAD

**Issue by Albonycal** [armbian/mirror#9]
can I just sync the armbian-apt (only packages) 
and would that be added to the official mirror list?
Thanks 
https://mirror.albony.xyz/

**Comment by igorpecovnik** [comment]
> can I just sync the armbian-apt (only packages) 

Yes
`rsync -av rsync://rsync.armbian.com/apt/`

> and would that be added to the official mirror list?

Drop some contact info when its up and ready:
https://www.armbian.com/#contact

**Comment by Albonycal** [comment]
Sorry for the delay, but the mirror is up now: https://mirror.albony.xyz/armbian/
*just the packages*
I sent the info here:  https://www.armbian.com/#contact
Additional info: it syncs every 59 minutes

**Comment by igorpecovnik** [comment]
Thank you! 

Enabled right away.

**Comment by Albonycal** [comment]
![image](https://user-images.githubusercontent.com/67057319/184079229-a1bf30dc-04ab-4ac3-8051-65d55a6eed26.png)
:+1:

**Comment by Albonycal** [comment]
This adds it to the readme.md 
https://github.com/armbian/mirror/pull/10
